name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Test with Maven
        run: mvn test -B

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3



