name: Build and Test

on: [push, pull_request]

env:
  MAVEN_HOME: /usr/share/maven
  MAVEN_REPO: /home/runner/.m2/repository

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
          
      - name: List directory contents
        run: ls

      - name: Build with Maven
        run: |
          cd my-project
          $MAVEN_HOME/bin/mvn package -Dmaven.repo.local=$MAVEN_REPO
#       - name: Test with Maven
#         run: mvn -B test --file pom.xml
