name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
          
      - name: List directory contents
        run: |
          cd src/
          ls

      - name: Build with Maven
        run: |
          mvn clean
          mvn compile
          mvn -B package --file pom.xml

#       - name: Test with Maven
#         run: mvn -B test --file pom.xml
