name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn -B test --file pom.xml
        
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0

